# Generated by Django 4.1.7 on 2023-10-05 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('emision', models.DateField()),
                ('vencimiento', models.DateField()),
                ('nit', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=100)),
                ('concepto', models.CharField(max_length=100)),
                ('descuento', models.CharField(max_length=20)),
                ('valor', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'Aprobado Jefe'), ('9', 'Rechazado')], default='0', max_length=2)),
            ],
            options={
                'permissions': [('subir_excel', 'subir_excel'), ('aprobar_pago', 'aprobar_pago')],
            },
        ),
    ]
