# Generated by Django 4.1.7 on 2023-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='empresa',
            field=models.CharField(default='Kosta Azul', max_length=20),
        ),
    ]
