# Generated by Django 4.2.6 on 2023-11-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0002_pagos_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('a', 'Ahorros'), ('c', 'Corriente'), ('o', 'Otra')], default='a', max_length=1)),
                ('numero_cuenta', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pagos',
            name='empresa',
            field=models.CharField(default='ka', max_length=20),
        ),
    ]
