# Generated by Django 4.2.6 on 2023-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0003_cuentasbancarias_alter_pagos_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasbancarias',
            name='estado',
            field=models.CharField(choices=[('0', 'Activa'), ('1', 'Inactiva')], default='0', max_length=2),
        ),
    ]
