# Generated by Django 4.2.6 on 2023-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_cuentasbancarias_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionPagosAprobados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('emision', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('concepto', models.CharField(blank=True, max_length=100, null=True)),
                ('descuento', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('cuentas_concatenadas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programacion_pagos_aprobados',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cuentasbancarias',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
