# Generated by Django 4.2.6 on 2023-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0006_acuerdos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
