# Generated by Django 4.2.6 on 2023-11-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0007_alter_acuerdos_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdos',
            name='nit',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acuerdos',
            name='dia',
            field=models.IntegerField(default=0),
        ),
    ]
