# Generated by Django 4.2.6 on 2024-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0008_acuerdos_nit_alter_acuerdos_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='revision',
            field=models.IntegerField(blank=True, default=0, help_text='0: Pendiente, 1: Revisado', null=True),
        ),
    ]
