# Generated by Django 4.2.6 on 2024-03-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0009_pagos_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdos',
            name='revision',
            field=models.IntegerField(blank=True, default=0, help_text='0: Pendiente, 1: Revisado', null=True),
        ),
    ]
